feat/MRUY-42-search-ui 최근 검색, 추천 검색 UI 구현
foreco-ibaji/Ibaji-App-version1 pull request #32
Opened 2024-02-08 08:55 UTC by tjdwns5063

![simulator_screenshot_01372C37-7F53-4B06-BAC1-4773BDBEE7AC](https://github.com/foreco-ibaji/Wiz-App-version1/assets/73011361/f2dd1cce-082c-4241-a60d-4e2a37dafe22)

- 최근 검색 및 추천 검색 UI 구현
- 최근 검색 기록 저장 및 삭제 기능 구현 (GetStorage 사용)

2024-02-09 12:54 UTC, kimwest00 requested changes
오 저번 리뷰에서 말씀드린 커밋 헤더 적용과 지라 티켓 브랜치, PR에 적용 해주셨네요! 빠른 피드백 반영감사합니다:) 이번 PR 공통 피드백은 아래에 남겨놓았습니다
[지라]
        - 커밋에서도 MRUY-티켓번호 를 작성해주시면 커밋도 링크가 됩니다! 지금의 경우 적용이 안되어도 상관이 없으나, 추후에 부득이하게 여러개의 티켓을 한 PR에 담을경우에는 도움이 될것같습니다
        - 자동완성화면과 결과화면이 아직 작업중이시라면, 하위이슈를 PR 단위로 분류해주시면 좋을것같아요! 지라에서는 검색기능 UI라고만 명시되어있어 추후에 혼동이 있을것같아서 제안드립니다
       
[이외에 협업을위한 문서화 관련 의견및 질문입니다]
    - 혹시 UI detail적인 부분은 아직 작업이전이신지 궁금합니다! 텍스트필드 색의 경우 placeholder와 style이 동일하여 제가 피그마에 코멘트로 질문 남겨두었습니다.! 이 이외에 예외처리가 필요한부분이 있다면 코멘트로 질문남겨주시면 좋을것같아요:)(ex 최근검색어 결과가없을경우 대체 ui혹은 텍스트)
    - 개별 코멘트에도 남겼지만, 검색 개발 Api가 개발이전이라 하드코딩한 부분은 //TODO, //FIXME 등의 주석 기능을 이용해서 표시해주시면 좋을것같습니다:)
    - 위젯에 주석달아주심 좋을것같아요! screen 단위는 생략하셔도 좋습니다:)

(사실 저도 혼자작업한 기간이 길어 문서화가 미흡한 부분이 많아서, 추가 작업 부분하며 빠르게 추가해두겠습니다ㅎㅎ)

2024-02-09 12:54 UTC, kimwest00 commented on lib/modules/search/widget/search_group_widget.dart
> +            for (int i = 0; i < lists.length; ++i)
옹 2줄이상 나열될 경우 GridView를 사용하지않고 Wrap을 사용해서 간단하게 해결할수있군요..! 배워갑니다 👍

2024-02-09 12:54 UTC, kimwest00 commented on lib/modules/search/widget/search_group_widget.dart
> +            ),
해당 SearchGroup 위젯은 추천검색어, 최근검색어 UI 그리기위해 구현한것으로 이해했는데,
그럼 요부분도 type에 따라 최근, 추천 검색어로 분기처리가 되어야하지 않나요?

2024-02-09 12:54 UTC, kimwest00 commented on lib/modules/search/widget/search_group_widget.dart
> +        mainAxisSize: MainAxisSize.min,
요거 실제로 구동해보니까 미묘하게 높이가 안맞는부분도 있어서,
crossAxisAlignment 중앙 설정으로 해주세요!
아래 Recommend도 동일한 피드백 남깁니다:)

2024-02-09 12:54 UTC, kimwest00 commented on lib/modules/search/widget/search_group_widget.dart
> +        child: Text(
타이틀을 최근,추천과 함께 공용으로 가져가기위해서 전체삭제 클릭리스너를 내부로 가져온구조로 보여요!
nullable 파라미터라서 따로 문제되진 않을 것 같지만, 개인적인 의견으로는 해당 `SearchGroup` 위젯은 추천,최근에서만 사용될것으로 보여서 두가지 타입밖에없고, 최근에서만 클릭리스너가 필요하다면 타이틀인 text위젯은 해당 위젯과 분리하는게 맞지않을까 생각됩니다!

2024-02-09 12:54 UTC, kimwest00 commented on lib/modules/search/view/search_view.dart
> +                ],
요건 api 연결이전이라서 우선 하드코딩해놓으신거죠!?
하드코딩한 부분은 //TODO, //FIXME 등의 주석 기능을 이용해서 표시해주시면 추후 작업에 있어
혼동하지 않을 수 있어 좋을 것 같습니다:)

2024-02-09 12:54 UTC, kimwest00 commented on lib/modules/search/controller/search_controller.dart
> +    current.sort((e1, e2) => -e1.dateTime.compareTo(e2.dateTime));
오 dateTime을 모델에 추가해서 정렬 로직까지 추가해주셨군요!
근데 정렬로직을 추가하지않아도 검색할때 리스트에 add하면, 최신순으로 쌓이지 않나요?
피드백은 아니고 궁금해서 질문남깁니다ㅎㅎ

2024-02-14 05:00 UTC, tjdwns5063 commented
> 오 저번 리뷰에서 말씀드린 커밋 헤더 적용과 지라 티켓 브랜치, PR에 적용 해주셨네요! 빠른 피드백 반영감사합니다:) 이번 PR 공통 피드백은 아래에 남겨놓았습니다 [지라] - 커밋에서도 MRUY-티켓번호 를 작성해주시면 커밋도 링크가 됩니다! 지금의 경우 적용이 안되어도 상관이 없으나, 추후에 부득이하게 여러개의 티켓을 한 PR에 담을경우에는 도움이 될것같습니다 - 자동완성화면과 결과화면이 아직 작업중이시라면, 하위이슈를 PR 단위로 분류해주시면 좋을것같아요! 지라에서는 검색기능 UI라고만 명시되어있어 추후에 혼동이 있을것같아서 제안드립니다
> 
> [이외에 협업을위한 문서화 관련 의견및 질문입니다] - 혹시 UI detail적인 부분은 아직 작업이전이신지 궁금합니다! 텍스트필드 색의 경우 placeholder와 style이 동일하여 제가 피그마에 코멘트로 질문 남겨두었습니다.! 이 이외에 예외처리가 필요한부분이 있다면 코멘트로 질문남겨주시면 좋을것같아요:)(ex 최근검색어 결과가없을경우 대체 ui혹은 텍스트) - 개별 코멘트에도 남겼지만, 검색 개발 Api가 개발이전이라 하드코딩한 부분은 //TODO, //FIXME 등의 주석 기능을 이용해서 표시해주시면 좋을것같습니다:) - 위젯에 주석달아주심 좋을것같아요! screen 단위는 생략하셔도 좋습니다:)
> 
> (사실 저도 혼자작업한 기간이 길어 문서화가 미흡한 부분이 많아서, 추가 작업 부분하며 빠르게 추가해두겠습니다ㅎㅎ)

- 커밋도 링크가 된다는걸 저도 끝나고 지라를 뒤적이다 알게돼서 다음엔 커밋에도 추가하도록 하겠습니다!

- 자동완성, 결과 화면은 작업을 했어야 하는데 본가에 내려와서 지내다보니 작업을 못했습니다ㅠㅠ 빠른 시일내에 만들도록 하겠습니다.

- UI 디테일은 텍스트 필드 부분만 제외하면 맞춘다고 맞췄는데 좀 다르다고 느껴지는 부분 있으시면 그에 맞게 수정해보겠습니다.

- 주석은 습관이 안되어 있어서 자꾸 빼먹게 되네요. 하드코딩한 부분에는 TODO 달아놓도록 하겠습니다~

2024-02-14 05:03 UTC, tjdwns5063 commented on lib/modules/search/controller/search_controller.dart
> +    current.sort((e1, e2) => -e1.dateTime.compareTo(e2.dateTime));
최신 기록을 맨 앞으로 보이게 하기 + 추후 날짜를 쓰게되지 않을까? 하는 생각에 일단 추가 해놓긴 했습니다.

보통 최근 검색어 기록들 보면 옆에 날짜도 보여주는 UI를 많이 봤어서 그렇게 활용 될수도 있지 않을까 해서 저렇게 구현했습니당

2024-02-14 05:04 UTC, tjdwns5063 commented on lib/modules/search/view/search_view.dart
> +                ],
넵 주석 추가해놓을게요!

2024-02-14 05:11 UTC, tjdwns5063 commented on lib/modules/search/widget/search_group_widget.dart
> +            ),
맞습니다! 제가 그 부분을 빼먹은것 같네요! 수정하겠습니다.

2024-02-14 05:24 UTC, tjdwns5063 commented on lib/modules/search/widget/search_group_widget.dart
> +        child: Text(
아 타이틀 위젯과 검색 결과 아이템 위젯을 분리하면 좋겠다는 말씀이 맞을까요??

예제 코드 첨부합니다.

```
children: [
  SearchTitle(title: ..., onSubtitleClick: () => {}, type: SearchType),
  SearchGroup(...)
]
```

2024-02-15 09:14 UTC, kimwest00 commented on lib/modules/search/widget/search_group_widget.dart
> +        child: Text(
넵 맞습니다! 근데 의견이라서 이 구조로 가도 될 것 같아요ㅎㅎ

2024-02-16 09:02 UTC, tjdwns5063 commented on lib/modules/search/widget/search_group_widget.dart
> +        mainAxisSize: MainAxisSize.min,
수정했습니다!

2024-02-16 09:04 UTC, tjdwns5063 commented
@kimwest00 

검색어 자동완성 ui 까지 작업했습니다! 여기까지 된거 머지하고 다음 작업 하는게 좋겠죠?? 🤔

2024-02-17 09:58 UTC, kimwest00 approved these changes
확인했습니다 수고하셨습니다~!
추후 작업은 PR 새로 열어서 해주시면 좋을것같아요
확인하면 성준님이 머지해주시면 감사하겠습니다:) @tjdwns5063

2024-02-18 06:13 UTC, merged